"""Discovery Report — the final deliverable combining all phases."""
from __future__ import annotations

from datetime import datetime
from typing import Any


def render_discovery_report(
    opportunities: list[dict[str, Any]],
    evidence_db_opps: list[dict[str, Any]],
    quantification: dict[str, Any],
    config: dict[str, Any],
) -> str:
    lines = [
        "# AI-Powered Fashion Wishlist Discovery Engine",
        "## Discovery Report",
        "",
        f"**Generated:** {datetime.now().isoformat(timespec='seconds')}",
        "",
        "---",
        "",
        "## Executive Summary",
        "",
        f"This report analyses {quantification.get('total', 0)} evidence packets across "
        f"{len(quantification.get('sources', []))} sources to identify why users wishlist "
        f"fashion products but fail to purchase within 30 days.",
        "",
        f"**Key findings:** {len(opportunities)} opportunity areas identified, "
        f"with {len([o for o in opportunities if o['score'] > 0.3])} high-priority.",
        "",
        "---",
        "",
        "## Ranked Opportunity Areas",
        "",
    ]

    for opp in opportunities:
        questions = opp.get("interview_questions", [])
        if isinstance(questions, str):
            import json
            try:
                questions = json.loads(questions)
            except (json.JSONDecodeError, TypeError):
                questions = [questions] if questions else []
        lines += [
            f"### {opp['rank']}. {opp['title'].replace('_', ' ').title()} (score: {opp['score']})",
            "",
            f"- **Frequency:** {opp.get('frequency', 0)} mentions",
            f"- **Behaviours:** {', '.join(opp.get('behaviours', [])) if isinstance(opp.get('behaviours'), list) else opp.get('behaviours', '')}",
            f"- **Barriers:** {', '.join(opp.get('barriers', [])) if isinstance(opp.get('barriers'), list) else opp.get('barriers', '')}",
            f"- **Evidence strength:** {opp.get('evidence_strength', 'medium')}",
            "",
            "**Score breakdown:**",
        ]
        breakdown = opp.get("breakdown", {})
        if isinstance(breakdown, str):
            import json
            try:
                breakdown = json.loads(breakdown)
            except (json.JSONDecodeError, TypeError):
                breakdown = {}
        for dim, val in breakdown.items():
            lines.append(f"  - {dim}: {val}")

        if questions:
            lines += ["", "**Interview questions:**"]
            for q in questions:
                lines.append(f"  1. {q}")
        lines += ["", "---", ""]

    lines += [
        "## Behaviour Frequency",
        "",
        "| Behaviour | Count | % |",
        "|-----------|-------|---|",
    ]
    for item in quantification.get("behaviours", []):
        lines.append(f"| {item['label']} | {item['count']} | {item['pct']}% |")

    lines += [
        "",
        "## Barrier Frequency",
        "",
        "| Barrier | Count | % |",
        "|---------|-------|---|",
    ]
    for item in quantification.get("barriers", []):
        lines.append(f"| {item['label']} | {item['count']} | {item['pct']}% |")

    lines += [
        "",
        "## User Segments",
        "",
        "| Segment | Count | % |",
        "|---------|-------|---|",
    ]
    for item in quantification.get("segments", []):
        lines.append(f"| {item['label']} | {item['count']} | {item['pct']}% |")

    lines += [
        "",
        "## Sources",
        "",
        "| Source | Count | % |",
        "|--------|-------|---|",
    ]
    for item in quantification.get("sources", []):
        lines.append(f"| {item['label']} | {item['count']} | {item['pct']}% |")

    lines += [
        "",
        "---",
        "",
        "## Methodology",
        "",
        "1. **Collection:** 9 sources (Google Play, App Store, Reddit, YouTube, Quora, forums, product reviews, Amazon, CSV)",
        "2. **Cleaning:** PII masking, spam/promo quarantine, out-of-scope language removal",
        "3. **Relevance:** keyword rules + optional LLM classifier (golden-set accuracy: 95.8%)",
        "4. **Extraction:** behaviour/barrier/unmet-need extraction with three-level distinction (said/inferred/concluded)",
        "5. **Segmentation:** rule-based segment assignment + KMeans theme clustering",
        "6. **Scoring:** weighted opportunity scoring across 8 dimensions",
        "",
        "---",
        "",
        "*Generated by the AI-Powered Fashion Wishlist Discovery Engine*",
    ]

    return "\n".join(lines) + "\n"
